import { SiteHeader } from '@/components/site-header';
import '@/styles/globals.css';
import { Space_Mono } from 'next/font/google';

const spaceMono = Space_Mono({ subsets: ['vietnamese'], weight: ['400', '700'] });

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spaceMono.className}>
        <SiteHeader/>
        {children}
      </body>
    </html>
  );
}
